msb.mqtt:
  server.enable: false
  forward: true
  client:
    id: ${random.uuid}
    server.uri: "tcp://localhost:1883"

logging.level: WARNING
logging.level.io.moquette: ERROR
logging.level.org.github.chibyhq.msb: DEBUG
  